### ISSUE TITLE
I used your design, hope it didn't bother you

### ISSUE THREAD

**Issue by xiangsudian** [sillyhatday/GAMEBOY-FLASHCART-MBC1-DISCRETE#1]
Hello,sillyhatday,I like your cart design very much ，so I copied your design. If your design is not allowed for commercial use, because I haven’t seen the relevant permission terms before, If I am not allowed to use. I will remove related products from my personal store. Thanks ，because I liked it, I also spent time optimizing your style design ,Sorry if it bothered you

So far(2023.6.16), I have removed all the product links on the store. Your work is great. In addition, if you do not encourage others to use your design in the future, especially for commercial use,I hope you can clearly indicate it.

Anyway, I am here to apologize to you for my mistake

**Comment by sillyhatday** [comment]
I like your design. I like your engraved chips. Just to have my name on your version somewhere to reference where the design come from would be nice. If you do that, then you can do whatever else you wish. Thanks.

**Comment by xiangsudian** [comment]
> I like your design. I like your engraved chips. Just to have my name on your version somewhere to reference where the design come from would be nice. If you do that, then you can do whatever else you wish. Thanks.

Thank you for your correction, I respect your principles (add your name logo like your new version2.0)
